#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/crest_device_service"
    username: "postgres"
    password: "1234"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  kafka:
    bootstrap-servers: "localhost:9092"

server:
  port: 9000

crest-device-service:
  database:
    # This key was used to encrypt the data in db/migration/test-data/V3__test_data.sql
    # If this is changed the test data also needs to be updated.
    encryption-key: "super-secret-key"
  kafka:
    pre-shared-key-consumer:
      id: "gxf-sng-crest-device-service"
      topic-name: "pre-shared-key"
    message-producer:
      topic-name: "crest-message"
  psk:
    change-initial-psk: false
    decryption:
      method: "RSA"
      private-key:
        1: |-
          -----BEGIN PRIVATE KEY-----
          MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQDAohMqAiQQG0yi
          gxo6llLkq8JSqbkgulslelgWZPgUMDmfGkvrk+waL04fgncHXAHHRtawEfWndj/9
          2Otx/UlguxbLzmNk2fgyk0+N1wocbmktmcp2jiy95ugOhSL4/E92tEF1syg92RUc
          02/pGQ7DCsfRNtK3wjJ6gprfyDs862cmLtmcj8sy/+zZFvAEATvMzOoCIq9j6VNK
          MRaXqh0BfF+45azj8xtVxyCw2tnjLhQNwSGfzkltz7SZ+RuBe4hZPqFVwNHT2+oi
          uV98sIfiJOPxph9FybBYNb7F/aSC1Ipje01kbMnnGmxg2s9BEZbSMKweSIFyn5P5
          TPqddatS4NZXdmnV5YtPu1pkiEfhJIxgGd1NfU9SIcHxRSFjh4SWfS9zxcPgW8ly
          aiADOMjz3JK/Cf7OT3NimUbBIVrUDIZvRJZEVC2lSegd7VL9C1pRVSmdrI1jYRa5
          xkd3k4+R7FlUB3MpcSKJ5I7mYtOUTfynO5VKclc0IMU9SLth2o/tnY+jb3oiWE0B
          NV//om71LKYWqfPMo/itsWnFwNd7cetS2cvtbcnjSCUnAIwwSn6TG52DQYI9xZpg
          7C31RPvRQqpY4acs556J9d0Ed8RbB78XZrugIyIgWvhRbFv2bD2I19YD+tScKggz
          tpvZx+OJEAibX0yNKCaCWsOq/h2DVwIDAQABAoICAAJ/9/SzG2m0GP4A6o25FrFO
          A1MUTck9ceJeIJeFzuxgJddJPZP8kvNSCtcA1++aA5Hk+vNFAGWgdLskHgYYLeQZ
          +XVCo+qSo5Rwcfdaw5BT5HyJguWf+berL/bERoxppdRaCYFwBkUrNIlvuwOQ5i6k
          zKwL5Jcq54HMgRsHW7FyMp/9uqg7+3yZcqbsk8fRhkelnyHQ9mq7A/AyC+OC+yZi
          SVG6dVBt/rxRvbxd0rcOiYcWKwwKXsyUhfj7kR5Qjpft5qUYwABaWcMCmdkh51mJ
          dgXUTJKYx/eVFvk1zfU+sd8RohL8EHC12JM3M7pZ8pWeuRUZhsiIhqCVHal+de8z
          IfZNhcXXIzUeC/rRv4u4mD+yUPeGD+uwfAxLr0OTkWFOKUkSGV936Z/h5fYW25JG
          /d/CtU5xxI7Q4NDrn+7Nevg1BbiaaQ5VYGpYhNDZz8bsKhy2oWfaQJ/+uoOh5tLz
          tVDAgHpvcxVbITPqEAcg6YpujkrXhHSzwweAcGZe8CWnwYoAoeDWyvjYbgEM3uvX
          l3WNKwWzYNNI5e/x2lUgtbg8B/IjRaroOPu4zZHwS2+iUtyrMtIURVI+zE09nDUm
          EPv8SI3sbFfutUyXYFkx/3FkbiFCCCO/LDXr6DO+B9ak6wAvzorPwLlIR7/GMJnw
          2PWVd2ldscRKsDz1qaOpAoIBAQDPw7v5Aj0ZZx5qjsOeiZ0HZTXGsCtwNZcs5oHK
          jB+E3x4Zoxi6tUU1g3IlO2PnfWLfSZN5OLFnO4RQUAYsQcYcWWpvFWSHhWEzf1IE
          5pFWs8Y0WKWwikyayRjMi36UMjXkDt10SfDu+IePKet5LF9BpcO55kyhiQ0qe4a6
          4bDbHJF4h1hJO5ecCaDiAqr8O2flf8l8oDRdqyc4Vfahuwh/47G12XOEqwhuz39c
          hEqEdTbbD7h9Q0p8VRUmTgF12degUvFJzojbwnjG5L80h5nOwAwOR1BFA1/pNw3r
          bxgbRE1WH0zoywq7SuerEnBSlkup3hIU494Bsex4Rgk29PEPAoIBAQDtWwRkjKk6
          mAAtGQaVDXArAg4C6SfC68CNsYMf0FVeUFNafa/1s/wiyLJNq0kivg5WL4JhC5kM
          CVa0OvegaSRjhvYWY/DELnA0SKxSoK7wz9xD302LtBTryNBGyY84t9qXyX81VJVj
          dN2yr8PmgpQIEw9sZUcECTuD1qbpYkB5DIpgkl/d48yaTp9Dm345jJVmqfIWIJ1r
          64A8NWrzrwqi6bJfVxwVbQ+OkbiPoCFphFcOltMGnpWl26PuC0jeMsDQNCwQr336
          BTJtqJDpQbMfOB3lKjWhzPJQ9XVvIQv/h2bshl+JnZ/KryO1vhIJR8hTYj3po5R6
          2IV+ZkKKoLk5AoIBAF8S7OPIGHmVbJ/KcM4NnyQRNoiTeW1BuMo9OUucz5eYGkgV
          EG3wIZmZaxSKlu8Ju8L+AlRIkzXwUF4IIKsD9kpmyIPIwFYbvR05uCix8fRBFARE
          RJ4Cy4dRWt3PP79FMtAH1WMvqudQJ4hl4HF00qpR1r0tHAgXlUTJfh/qw2mhKxiC
          pu3sLTakWVDTc7c04BhvX55+GTh759ipzdC4q+0KHvpeZbRiJ9u9bETD7O2sTcv0
          57G6p006ChGbRKPPahLdobjqoEogNfCeILlDDClGTL4D+EF8h9lK7j28esWPfexZ
          KnKk52ZJorXwHCJO0JUNIC0bES6pYtKvCexyLhUCggEAA2Ab++IUNgUbW4jTkyMR
          yUrKMDhonFkF7/3qQ3WPATxbMxo+elwI5eW8w2YAMEJLqeYbEI49qvInDYEZLGrS
          Xaf5r+/T6LZQWi3+ZV5rnnkWRNDUJXx2H7RHYfpT0xaqQSZYbMW7KiLrVDMzsf+B
          Y2wB+CSokeIfuow+62q+R/pprV3nhxxKOJeNpER90wuwxDj+fFoSYwqCVFjeIIEI
          wbBZHQn8GEHoyro/yasZTorXQhna/mka77Tj6+q1KpPGMi/LwKD+RaP1R6HyDZ8l
          kPgXVL747Egh2gzjkqUBqqyeRhbTHP3k29kJxPfjAcbHjogDIWN2JRkXLOj/YUFP
          4QKCAQBDZYuG36eOMr9Wtbv+ihTypr2DWEGAh8dcR3upuOKYRmg/4NKAUcJEMlOi
          DtrMl/ODPpxgEL1V6e3cbAtu2nNqzmTrmhgo3YsyJQQxqnQzLpMTd6U6jwkmOYO9
          gS7Xz5Jc4hzE14bWr/Y3lzp5pS22DyFmOGW696x5XBPhiFUzzOABcmPtRsvEHNX7
          c/klvUlULKGEtzCA3w6nvO6vCDDzhYgBOeZP9+1fiNZMZDxpsDpXg8sxqIli646Y
          JioyvmPWYN9Thi/V1WWwso3XknJC2tzeGx7GWkqK82wmN15EoI5zgRQp+Gezkmlb
          eoVhHqH4WVk0P0FoFuugg+8LcMFb
          -----END PRIVATE KEY-----
