spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/crest-device-service-test"
    username: "postgres"
    password: "1234"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  kafka:
    bootstrap-servers: "localhost:9092"

server:
  port: 9000

crest-device-service:
  database:
    encryption-key: "super-secret-key"
    dev-initial-psk: "ABCDEFGHIJKLMNOP" #Should be the same as the PSK in the simulator only relevant for dev
    dev-device-identity: "867787050253370" #Should be the same as the identity in the simulator only relevant for dev
  kafka:
    configuration-consumer:
      id: "gxf-sng-crest-device-service-maki"
      topic-name: "maki"
    message-producer:
      id: "gxf-sng-crest-device-service"
      topic-name: "crest-message"
