spring:
  kafka:
    bootstrap-servers: "localhost:9092"

server:
  port: 9000

crest-device-service:
  kafka:
    id: "gxf-sng-crest-device-service"
    topic-name: "crest-message"
  http:
    endpoint: "coap"
