#SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/crest_device_service"
    username: "postgres"
    password: "1234"
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "gxf-sng-crest-device-service"

# Local testing certificates
mutual-tls:
  keystore:
    private-key: "classpath:ssl/dev-device-service-key.pem"
    certificate: "classpath:ssl/dev-device-service-cert.pem"
  truststore:
    certificate: "classpath:ssl/dev-proxy-cert.pem"

# port for proxy, using mutual TLS
server:
  port: 9000

config:
  # port for web client
  web-server:
    port: 9001

kafka:
  consumers:
    pre-shared-key:
      topic: "pre-shared-key-internal"
    command:
      topic: "command-internal"
  producers:
    device-message:
      topic: "crest-device-message"
    command-feedback:
      topic: "command-feedback-internal"
    firmware:
      topic: "firmware-internal"
      key: "firmware"

database:
  # This key was used to encrypt the data in db/migration/test-data/V3__test_data.sql
  # If this is changed the test data also needs to be updated.
  encryption-key: "super-secret-key"
psk:
  change-initial-psk: false
  decryption:
    method: "RSA"
    # Test decryption key for psk's.
    private-key:
      1: |-
        -----BEGIN PRIVATE KEY-----
        MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDyWCnRzKbTnYEySkzElzk2ahvijBvJqpYlRDUi9GCk9VL6nLCuHjB4LBY6nwMyMalMRwu6UgYiBcwqW8GPEy8k+j1iuuNzzzDlRxprQi5ZZZBYtF7tX0ImO/xArT/on1CTGsR9aIb3Joq0leEEUT+4vswPvtx2JMq3HmTbEZFNBn9HHCLs9iJ0F7VUCxJJgxtCgnHR+4TczsLHAryYgTTx3Vwx5oJRe4nw9dH0krxiGx86TA+gQqU02tPYspRNF2obZyfLpjEnagh29BpGtWsuaHKYSxRKqU3vAuKV0YOR6E36iXJj3TNd17BYwdMKiBWGV7kqGgdoFAtCHdSB6UZSBuY+Wg3DDs8IKcXK08FGrJcfvBcxhTFrl7dQB/O5Dnl2Rwbbjq0w7+aQCINL+VczgblxAmQn9/Ff4qmjsinWwDWJKyqcp6nQzjypKpHhJaViMy9T5zruu5axN7pS8749LEvp4WiGPAXca2C5dCLU7CSNyHMOZD8oVwfXukV15cxnKcbcl7XGRL8LIuXKG6/nLt/Zl02W6WSpmB9dhMz9jYYunownK9An7UQVWG4YYRcLzjQm19DA12Mnj13mCyN0Hj0GmaJg4kf202SAk2ZtnVQL+50caA0PardrKHX99RpVWvJkqubA//2kthkkpImAr0zKQ+TS/3hLpnZxbjISfQIDAQABAoICAC259GQVcxnlM2o3ij4i0YUCpvHLYXffA9cSxFrs1OpzLp3CYHTuFdOq7+POOpZnN+xAUIZusSEMyn3ok8BJDKFzxQ7iuAWTP8TXMnUwBtpP11lhaTLtQShBM8LJXdBo9RVYnOATz7mFEHFsAUnlAbq8Z3kGGIeDQCumpL2QFkQ8GFpkxPNEqvIQQiLSNvhfcE6PmeXWyTY3nhlaWxcEdCa5z4pL1eWFg5zPaTb2U+zH9M+1Z9JjmNP9ATF3WpOkOh1jDKd4m3g2IdQ+EVIrq4ZVZ1/0dKb0xJN3TiUaI/LtK/98nTSaGXXYu3m30rf/Pt57IWFACYs6Evi986myiBWWmRmbz1lyS6g+LurM/WwSHBLr5A4BMSS8Ga0hNdiVwdOkdrpRuPXrKpQMik2WIiVN6YmNe+ZJo2njHyw7hK/xV77rRieV0i1UBMYlriqpp0FRCEY2yuvPT/wjH05nsccws0wemO3OK2MLGtARSDAWtToHVn0WTxjKa+WxymSApl8HH3TyqqqrgVeuBgQfq2i2A2iNT0yJgYxaX6L+Eki/EoPqQGobJodx8qU8gNcFb0kE7lIh/0705S0ygQ/LJrwG5nxTg/1AZZIUpsyXk3yMHtAqWSdDE6YrFyePoJNJ1ldlBAgHajigimbCGH/TamxDRXELGqn+2CufDdhgXePBAoIBAQD/QufAZUOfaPapzVuhMOZmgCZHMS7KUL1ltcf2FND6r+cLoujFoHvzv9bXECuYyC8qwdzW776y7d71BuU7m3g5ha0OK8iz0MZYkVuFoRvdr2ym4OslgzRTM14nntHtL0B2ZhDfK574VvQNOj8R2PwfygicClrpLSnTjNF8wu7TWmIWHlSsm2O5eJNdu428ia1fe/BI3txQ6WnMOFMMtnLigWz3+oapE8MattEApuyj6RgDnitk9rea3K3DgcbjS/QFJ35k0QqBpvJFYlshr5Sd+baTj/rIrO6RnB3perwWSe2hf74kPBXWL1SXiXC9xT3msTKDsLkOBmtSy7Q8oV+9AoIBAQDzC7B4kP16dkMQiWnH1WbPVTsdZohw+kJ8gVUqQ4YwdkALcPmCbEgWiAJ2I1JNXN86xMP/NFeZbwVNsX9Xx1EoLpls6P1o036lwjJYEkaDlySf2kOS7COiCGFPIGT1WeICmFjWaPhnZV5ZwQhzqazuoVE8MbT1wPU+ZevN/rG3ztcczx+x7mFcRogDkXG+X86C8HFTnHf9aKVZKPRqssFGAFI8SAh5/IMe7mYHFsv22ZINFcls2WfWNNWLnXhiLNzgv2KJ00seJFP61oF/72S/FdgnaCRIgVB0DUSA+PiwfBcPiO+GC6x6R88Pn9t8byupBv1x5yi1e3Oqek1a7EnBAoIBADLYIs1h3kxcXfWIoB3FXb9A+17m3wkReAhQYxoTH2UvsHfS5UaoJshwh9yirexqw2pi3xg4/OUrGGP6EaMD3rimdcgC1KFsjnWJzo8ZfjF0BdJfrrb0IXIJI1IFAo+Z/98ViXrKd4nD2CziUzm83MuANKLQNTeI9XHb9MZDFcsnj64UMI2JDh4ddE0RVLQfQFdqmnwJWB0NwTMabQB1PwD7AreKQVRgSVaC37KfjTdA8LWXxdEAi6XfGwV8Th9sO5jjOvvd35ffpxZG9xwImzO0T7eo0C00tPhv/k1JUzmlVB39EeSpyze0icb9a2WBakkPNp6gjtvKT4pYZPhGtIkCggEBAMhwO3kzGdiE74oTyUkklUUn5Ti59ow1198WSkYwqdoNq4PECAGni0wJnv4O4zEqBm9RFtLBN/0xsg4A9CRQHH4m8CEBhPuOcEQDg8FeUQj0/R9XwaLJXBmlD5tR+/Dbz6iUO6+XokSjNMyQhYfdxuCF6Zja5YJHP/nV1EJuaeJMktsPdfQnw+N1x3Yp3MRD/uu9n7h0sgAq7TI6tFfKU9qHKUrNnS/9L6WytjHiexN5Gxnvfc5m/VuK9xHNLBrLJN20+G7x8mFJVHjprqLzqwJr4XeeS04AV3ld98DlkzL5I4uMQv0pY3T1A66/ByP4Cum6+gmVudzxktJlSqZReAECggEBAMWDF4KN7irjvIHTuiU8X+8296gaPyQLv9j8VNGxD0Z/n44eAWjUnvsqW9jpaa3cw9GgnZRqPK8OPSx4vS8zLcnRIwmbgPz7W944DJKHjK96x6d7AUrFidjBBIIfzNTF7s/usYT6WMOBuC2pmVhdSj/RlVcWCYH2DErJne9Jywj46C8LVFZeNa1qO8EKK8/aKzDpSNC+zSvBKmapAEMJZ3MyXPYJuNwMhVCeaKscAJB8SLfTaUFKXSBMc9ZVqLTKis5OKsWucqzucb0ljvR+02F/LY+oY3SM1gAqH/eAQD8xBUXQAzkuFQR7SfQ7hhCiigEiidP70FBOeQyIQGJ4W5Y=
        -----END PRIVATE KEY-----
message:
  max-bytes: 1024

logging:
  level:
    org.gxf.crestdeviceservice: debug
