spring:
  kafka:
    bootstrap-servers: "localhost:9092"

server:
  port: 9000

crest-device-service:
  kafka:
    configuration-consumer:
      id: "gxf-sng-crest-device-service-maki"
      topic-name: "maki"
    message-producer:
      id: "gxf-sng-crest-device-service"
      topic-name: "crest-message"
