spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

crest-device-service:
  kafka:
    configuration-consumer:
      id: "gxf-sng-crest-device-service-maki"
      topic-name: "maki"
    message-producer:
      topic-name: "topic"
